import type { Config } from "tailwindcss";

// Color tokens copied verbatim from Stitch DESIGN.md to match the mockups
// pixel-for-pixel. Do not edit without updating the corresponding screen
// designs.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0a1420",
        surface: "#0a1420",
        "surface-dim": "#0a1420",
        "surface-bright": "#303a47",
        "surface-container-lowest": "#050f1b",
        "surface-container-low": "#121c29",
        "surface-container": "#16202d",
        "surface-container-high": "#212b38",
        "surface-container-highest": "#2c3543",
        "on-surface": "#d9e3f5",
        "on-background": "#d9e3f5",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#d9e3f5",
        "inverse-on-surface": "#27313e",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        secondary: "#4de082",
        "on-secondary": "#003919",
        "secondary-container": "#00b55d",
        "on-secondary-container": "#003e1c",
        tertiary: "#ffb3b0",
        "on-tertiary": "#670211",
        "tertiary-container": "#ea6767",
        "on-tertiary-container": "#5b000d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#6dfe9c",
        "secondary-fixed-dim": "#4de082",
        "on-secondary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#005227",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b0",
        "on-tertiary-fixed": "#410006",
        "on-tertiary-fixed-variant": "#881d24",
        "surface-variant": "#2c3543",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "16px",
        margin: "24px",
      },
      fontFamily: {
        "data-md": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        serif: ["Charter", "Georgia", "serif"],
      },
      fontSize: {
        "data-md": ["14px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "data-lg": ["16px", { lineHeight: "1.2", fontWeight: "500" }],
        "data-sm": ["12px", { lineHeight: "1.1", fontWeight: "400" }],
        h1: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
